### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/fletd-0.3.2-linux-amd64.tar.gz'

### ISSUE THREAD

**Issue by jcleng** [flathub/org.openandroidinstaller.OpenAndroidInstaller#1]
```shell
┌💁  jcleng @ 💻  nixos in 📁  ~
└❯ flatpak run org.openandroidinstaller.OpenAndroidInstaller
Traceback (most recent call last):
  File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3.10/http/client.py", line 1447, in connect
    super().connect()
  File "/usr/lib/python3.10/http/client.py", line 941, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/usr/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/flet/flet.py", line 492, in _download_fletd
    urllib.request.urlretrieve(flet_url, temp_arch)
  File "/usr/lib/python3.10/urllib/request.py", line 241, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 557, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 749, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/usr/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/openandroidinstaller/openandroidinstaller.py", line 329, in <module>
    startup()
  File "/app/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/app/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/app/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/app/lib/python3.10/site-packages/openandroidinstaller/openandroidinstaller.py", line 322, in startup
    ft.app(
  File "/app/lib/python3.10/site-packages/flet/flet.py", line 102, in app
    conn = _connect_internal(
  File "/app/lib/python3.10/site-packages/flet/flet.py", line 192, in _connect_internal
    port = _start_flet_server(
  File "/app/lib/python3.10/site-packages/flet/flet.py", line 292, in _start_flet_server
    fletd_path = _download_fletd()
  File "/app/lib/python3.10/site-packages/flet/flet.py", line 500, in _download_fletd
    os.remove(temp_arch)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/fletd-0.3.2-linux-amd64.tar.gz'

```

```
└❯ flatpak --version
Flatpak 1.14.0

OS: NixOS 22.11.3253.eac7da7b519 (Raccoon) x86_64
Kernel: 5.15.103 
```

**Comment by tsterbak** [comment]
Hi, are you sure you granted network access to the flatpak?
At least I had the same issue when I tried it without it.

**Comment by axtloss** [comment]
> > Hi, are you sure you granted network access to the flatpak? At least I had the same issue when I tried it without it.
> 
> It may not be possible to download, in CN

Yes that is most likely the issue, as I am not able to recreate this issue at all.

It also appears to be an issue with flet directly, as I cannot find the code where OpenAndroidInstaller fetches this. But @tsterbak probably knows more about that.

**Comment by tsterbak** [comment]
I will check with the flet developers. Maybe this is something that can be integrated in the flatpak directly.

**Comment by tsterbak** [comment]
I this resolved with the latest release 0.5.4-beta.1?
